### ISSUE TITLE
Cannot build with source on Windows 7

### ISSUE THREAD

**Issue by thangld322** [orlandohill/waxeye#90]
Firstly, thanks for such an amazing tool!

I downloaded and used the Waxeye 0.8.0 on Sourceforce but this old version has an issue that it cannot parse long string:

> RuntimeError: maximum recursion depth exceeded
Since this version is quite old, I hope that the current source fixed that issue. So I try to build Waxeye follow User Manual guide but I cannot install it.
`C:\Users\thangld_anm\Downloads\waxeye-master\waxeye-master>build\exe.bat

C:\Users\thangld_anm\Downloads\waxeye-master\waxeye-master>SET PLTCOLLECTS=";C:\Users\thangld_anm\Downloads\waxeye-master\waxeye-master\build\..\src\scheme\"

C:\Users\thangld_anm\Downloads\waxeye-master\waxeye-master>"C:\Program Files\Racket\raco.exe" exe "C:\Users\thangld_anm\Downloads\waxeye-master\waxeye-master\build\..\src\waxeye\waxeye.rkt"
c:\users\thangld_anm\downloads\waxeye-master\waxeye-master\src\waxeye\main.rkt:7:9: collection not found for module path: waxeye/ast
  collection: "waxeye"
  in collection directories:
   C:\Users\thangld_anm\AppData\Roaming\Racket\6.12\collects
   C:\Program Files\Racket\collects
   C:\Users\thangld_anm\Downloads\waxeye-master\waxeye-master\build\..\src\scheme\
   ... [165 additional linked and package directories]

C:\Users\thangld_anm\Downloads\waxeye-master\waxeye-master>"C:\Program Files\Racket\raco.exe" distribute . "C:\Users\thangld_anm\Downloads\waxeye-master\waxeye-master\build\..\src\waxeye\waxeye.exe"
with-input-from-file: cannot open input file path: C:\Users\thangld_anm\Downloads\waxeye-master\waxeye-master\build\..\src\waxeye\waxeye.exe
  system error: The system cannot find the file specified.; errid=2

C:\Users\thangld_anm\Downloads\waxeye-master\waxeye-master>DEL "C:\Users\thangld_anm\Downloads\waxeye-master\waxeye-master\build\..\src\waxeye\waxeye.exe"
Could Not Find C:\Users\thangld_anm\Downloads\waxeye-master\waxeye-master\src\waxeye\waxeye.exe`
I have two questions:
1. Did the new version fix my issue?
2. How can I build this on Windows?

Thank you so much.

**Comment by glebm** [comment]
1. The recursion problem is fixed in the JavaScript runtime, but not in the C runtime.
2. Update the exe.bat with this fix: https://github.com/orlandohill/waxeye/pull/91/files

**Comment by thangld322** [comment]
@glebm 
Thanks for replying!
I want to use Python runtime. Is it fixed in Python?

**Comment by orlandohill** [comment]
Hi,
Sorry, the problem still needs to be fixed for Python. The current TypeScript code needs to be ported to Python, while making sure the public API remains unchanged.

We're looking for volunteers, if you'd like to help.
